### ISSUE TITLE
RECEKTED! REJECTED! RECEKTED! REJECTED! RECEKTED! REJECTED! RECEKTED!

### ISSUE THREAD

**Issue by hsynercn** [namiduru/Linux_CLI#1]
**REJECTED** 
@namiduru , bu kodu pakete sokarsak Cuihao bize çok kızar code review DTSi açarlar. Bu akşam bir paketçi ve testçi arkadaşa rica edicem kalacaklar tekrar paket çıkarıp test edelim paket pushlayalım. Test bitmeden sen de eve gitmezsin.  Akşam da taksi kullanmazsan sevinirim, zaten senin ev yakındı.

**Comment by namiduru** [comment]
Huseyin Lutfen m 102 ye gelebilir misin?
